/**
 * @scalar GENERATED_CODE
 * 
 * This file is auto-generated by the buildMdxElements function
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * This file can be safely added to the .gitignore file if desired.
 */

import React from 'react'

import scalarComponents from 'scalar-mdx-components'

export const Hello = React.lazy(() => import('./../snippets/Hello.jsx' as any).then((m: any) => ({ default: m.default ?? m['Hello'] })))

export const components = {
  'Hello': Hello,
}

/**
 * This function is used to inject the components into the JSX context during the page build.
 * 
 * It is used to avoid explicit imports of components in the MDX files.
 */
export function useMDXComponents(_components: Record<string, React.ComponentType<any>> = {}) {
  return {
    ..._components,
    ...components,
    ...scalarComponents,
  }
}