/**
   * @scalar GENERATED_CODE
   * 
   * This file is auto-generated by the buildMdxElements function
   * DO NOT EDIT THIS FILE MANUALLY
   * 
   * This file can be safely added to the .gitignore file if desired.
   */
  export * as React from 'react'

  export { jsx } from 'react/jsx-runtime'

  export { createRoot } from 'react-dom/client'
  export { flushSync } from 'react-dom'